language: node_js

env:
  - CI=true

install:
  - npm i -D

jobs:
  include:
    - stage: Test
      script: ./shell-scripts/test.sh
    - stage: Docker image build and publish
      script: ./shell-scripts/docker_build.sh
    - stage: Deploy to Heroku
      script: ./shell-scripts/deploy_heroku.sh
    - stage: Migrate database
      script: ./shell-scripts/migrate_database.sh
    - stage: Publish code coverage
      script: ./shell-scripts/publish_coverage.sh

script:
  - npm run build
  - npm test -- --coverage --ci --coverageReporters=text-lcov | coveralls
