language: python

env:
  - CI=true

install:
  - pip install awscli

jobs:
  include:
    - stage: Test
      script: ./shell-scripts/run-tests.sh
    - stage: Build docker image
      script: ./shell-scripts/build-docker-image.sh
    - stage: Deploy to Heroku
      script: ./shell-scripts/deploy-to-heroku.sh
    - stage: Publish code coverage
      script: ./shell-scripts/publish-code-coverage.sh

script:
  - npm run build
  - npm test -- --coverage --ci --coverageReporters=text-lcov | coveralls
