version: '3.4'
services:
  stub-server:
    build:
      context: .
      target: build
    command:
      - npm run stub-server
    ports:
      - '3000:3000'
    container_name: http_quest_stub_server
  build:
    build:
      context: .
      target: build
    ports:
      - '8000:8000'
    container_name: http_quest_frontend_build
    volumes:
      - ./build/:/app/build
    depends_on:
      - stub-server
  test:
    build:
      context: .
      target: test
    container_name: http_quest_frontend_test
    volumes:
      - .coverage:/app/.coverage
    depends_on:
      - build
  publish-coverage:
    build:
      context: .
      target: test
    container_name: http_quest_frontend_test_publish
    volumes:
      - .coverage:/app/.coverage
    command: npm run coveralls .coverage
    depends_on:
      - build
  app:
    build:
      context: .
      target: prod
    command:
      - npm run build-watch
    ports:
      - '8000:80'
    container_name: http_quest_app
    environment:
      - PORT=80
    volumes:
      - ./build/:/usr/share/nginx/html/
    depends_on:
      - stub-server
      - build
